3 black-cards added, ~15 white cards added
libscie/cards-against-science pull request #1
Opened 2017-03-14 08:01 UTC by turboKnul

2017-03-14 08:03 UTC, chartgerink requested changes
Skitterend 💯 Nog 1 wijziging nodig voor accept. I hold the power MUAHAHAH

2017-03-14 08:03 UTC, chartgerink commented on white-cards.txt
> +Fraude
Merde fraud a la French!

2017-03-14 08:03 UTC, chartgerink commented on white-cards.txt
> +Your mom
Sexist, please remove or add "Your father"

🤒

2017-03-14 08:05 UTC, chartgerink commented
Misschien moeten we @RobbieVanAert ook betrekken hierin?

2017-03-14 08:13 UTC, turboKnul commented
Ja uitteraard!

2017-03-14 9:05 GMT+01:00 Chris Hartgerink <notifications@github.com>:

> Misschien moeten we @RobbieVanAert <https://github.com/RobbieVanAert> ook
> betrekken hierin?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libscie/cards-against-science/pull/1#issuecomment-286348965>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVT3TyRrN89nDSp_BdgvKN-unk34aP9Yks5rlkpYgaJpZM4McPC2>
> .
>

2017-03-14 08:17 UTC, turboKnul commented
# Cards have been adapted to the likings of the master of lulz

2017-03-14 09:00 UTC, chartgerink approved these changes

2017-03-14 09:01 UTC, merged

2017-03-14 09:24 UTC, RobbievanAert commented
Ik heb iets meer uitleg nodig om te begrijpen waar dit over gaat. Een Nobel prijs gaat dit 1-2-3 niet winnen vrees ik...

Wel een mooie foto turboKnul ;-)

2017-03-15 11:31 UTC, turboKnul commented
Ja dankje, ik ging niet zozeer voor mooi, maar voor intens. Ik denk dat dat ook wel gelukt is. Het spelletje gaat alsvolgt: 
# regels van de game
- iedereen heeft witte kaartjes in zijn hand met woorden (zelfs standige naamwoorden, werkwoorden)
- Speler 1 is aan de beurt en trekt een zwarte kaart: bv  ``` er staat een _ in de gang ```
- Dan moeten de andere spelers de blank invullen met iets wat ze grappig vinden
- Degene van de de zwarte kaart is bepaald wie de grappigste  combinatie heeft gemaakt, die krijgt dan vervolgens die zwarte kaart
- Degene die op het einde van de game de meeste zwarte kaarten heeft, is de winaar van cards against science

TL:DR een leuke party game voor de doorgewinterde scientist